on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
name: Deploy
jobs:
    production:
        name: Upload Production
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Upload Production
              uses: SamKirkland/FTP-Deploy-Action@2.0.0
              env:
                  FTP_SERVER: ${{ secrets.FTP_SERVER }}
                  FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
                  FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
                  LOCAL_DIR: ./docs/
                  REMOTE_DIR: /public_html/traveler20.site/
